# OpenClaw Gateway Configuration
# Token-based authentication for Control UI

gateway:
  controlUi:
    # Allow token auth without device pairing
    dangerouslyDisableDeviceAuth: true

    # Allow token auth over HTTPS (behind Cloudflare tunnel)
    allowInsecureAuth: true

  # Token authentication
  auth:
    token: "97f7c2e8dd9e9524629445383662506a067949a71dfad0d95edbcbbc2834f587"

  # Trust Cloudflare proxy headers
  trustedProxies:
    - "127.0.0.1"
    - "::1"

# Agent configuration
agents:
  defaults:
    # Route web channel to Odin orchestrator
    backend: odin

# Odin orchestrator settings
odin:
  orchestrator:
    url: "http://localhost:5105"
    timeout: 30000
    maxRetries: 3
